# Generated by Django 3.1.5 on 2021-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lun', 'Lundi'), ('Mar', 'Mardi'), ('Mer', 'Mercredi'), ('Jeu', 'Jeudi'), ('Ven', 'Vendredi'), ('Sam', 'Samedi'), ('Dim', 'Dimanche')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
