# Generated by Django 3.1.5 on 2021-02-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210209_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day_of_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.week'),
        ),
    ]
